// Product categories — the 5 material families kept per client request
// (PVC / PUR / KLIN / metal / sujungimo elementai), names translated to
// Lithuanian. Generated by scripts/scrape-generate.mjs — do not edit by hand.
// `parent` is the parent category id, or null for a top-level category.

export type Category = {
  id: string;
  name: string;
  slug: string;
  parent: string | null;
};

export const categories: Category[] = [
  { id: "rukava-z-polihlorvinilu", name: "PVC žarnos", slug: "rukava-z-polihlorvinilu", parent: null },
  { id: "armovani-metallospiralyu-ua", name: "Armuotos metalo spirale", slug: "armovani-metallospiralyu-ua", parent: "rukava-z-polihlorvinilu" },
  { id: "armovani-pvh-stallyu-ua", name: "Armuotos PVC spirale", slug: "armovani-pvh-stallyu-ua", parent: "rukava-z-polihlorvinilu" },
  { id: "rukava-z-poliuretanu", name: "PUR žarnos", slug: "rukava-z-poliuretanu", parent: null },
  { id: "armovani-metallospiralyu", name: "Armuotos metalo spirale", slug: "armovani-metallospiralyu", parent: "rukava-z-poliuretanu" },
  { id: "armovani-pvh-stallyu", name: "Armuotos PVC spirale", slug: "armovani-pvh-stallyu", parent: "rukava-z-poliuretanu" },
  { id: "bez-spirali", name: "Be spiralės (FLAT)", slug: "bez-spirali", parent: "rukava-z-poliuretanu" },
  { id: "rukava-typu-klyn", name: "KLIN tipo žarnos", slug: "rukava-typu-klyn", parent: null },
  { id: "metalorukavy", name: "Metalinės žarnos", slug: "metalorukavy", parent: null },
  { id: "metalorukavy-z-oczynkovanoyi-stali", name: "Iš cinkuoto plieno", slug: "metalorukavy-z-oczynkovanoyi-stali", parent: "metalorukavy" },
  { id: "metalorukavy-z-nerzhaviyuchoyi-stali-ua", name: "Iš nerūdijančio plieno", slug: "metalorukavy-z-nerzhaviyuchoyi-stali-ua", parent: "metalorukavy" },
  { id: "elementi-ziednannya", name: "Sujungimo elementai", slug: "elementi-ziednannya", parent: null },
];

const byId = new Map(categories.map((c) => [c.id, c]));
export const categoryById = (id: string): Category | undefined => byId.get(id);
export const childrenOf = (parentId: string): Category[] =>
  categories.filter((c) => c.parent === parentId);
export const topCategories = (): Category[] => categories.filter((c) => !c.parent);

// Walk to the top-level ancestor of a category.
export function topAncestor(id: string): Category | undefined {
  let cur = byId.get(id);
  const seen = new Set<string>();
  while (cur && cur.parent && byId.has(cur.parent) && !seen.has(cur.id)) {
    seen.add(cur.id);
    cur = byId.get(cur.parent);
  }
  return cur;
}
