// Product categories — full hierarchy mirrored 1:1 from the original site
// (https://rikomarket.com.ua), names translated to Lithuanian. Generated by
// scripts/scrape-generate.mjs — do not edit by hand.
//
// Top-level categories are either material types (PVC/PUR/KLIN/metal/fittings/
// "Kita") or application areas (woodworking, ventilation, …). `parent` is the
// parent category id, or null for a top-level category.

export type Category = {
  id: string;
  name: string;
  slug: string;
  parent: string | null;
};

export const categories: Category[] = [
  { id: "derevoobrobna", name: "Medienos apdirbimas", slug: "derevoobrobna", parent: null },
  { id: "dlya-virobnicztva-mebliv", name: "Baldų gamybai", slug: "dlya-virobnicztva-mebliv", parent: "derevoobrobna" },
  { id: "dlya-verstativ-chpu", name: "CNC staklėms", slug: "dlya-verstativ-chpu", parent: "derevoobrobna" },
  { id: "dlya-struzhkopilotyagiv", name: "Drožlių siurbliams", slug: "dlya-struzhkopilotyagiv", parent: "derevoobrobna" },
  { id: "dlya-pelet", name: "Granulėms", slug: "dlya-pelet", parent: "derevoobrobna" },
  { id: "dlya-obrobki-masiviv", name: "Masyvų apdirbimui", slug: "dlya-obrobki-masiviv", parent: "derevoobrobna" },
  { id: "dlya-ruchnogo-zastosuvannya", name: "Rankiniam naudojimui", slug: "dlya-ruchnogo-zastosuvannya", parent: "derevoobrobna" },
  { id: "elementi-ziednannya", name: "Sujungimo elementai", slug: "elementi-ziednannya", parent: null },
  { id: "himichna-promislovist", name: "Cheminė pramonė", slug: "himichna-promislovist", parent: null },
  { id: "dlya-himichnih-laboratorij", name: "Cheminėms laboratorijoms", slug: "dlya-himichnih-laboratorij", parent: "himichna-promislovist" },
  { id: "dlya-himichnih-vipariv", name: "Cheminiams garams", slug: "dlya-himichnih-vipariv", parent: "himichna-promislovist" },
  { id: "dlya-galvniki", name: "Galvanikai", slug: "dlya-galvniki", parent: "himichna-promislovist" },
  { id: "metalorukavy", name: "Metalinės žarnos", slug: "metalorukavy", parent: null },
  { id: "metalorukavy-z-oczynkovanoyi-stali", name: "Iš cinkuoto plieno", slug: "metalorukavy-z-oczynkovanoyi-stali", parent: "metalorukavy" },
  { id: "metalorukavy-z-nerzhaviyuchoyi-stali-ua", name: "Iš nerūdijančio plieno", slug: "metalorukavy-z-nerzhaviyuchoyi-stali-ua", parent: "metalorukavy" },
  { id: "rizne", name: "Kita", slug: "rizne", parent: null },
  { id: "rukava-typu-klyn", name: "KLIN tipo žarnos", slug: "rukava-typu-klyn", parent: null },
  { id: "rukava-z-polihlorvinilu", name: "PVC žarnos", slug: "rukava-z-polihlorvinilu", parent: null },
  { id: "armovani-metallospiralyu-ua", name: "Armuotos metalo spirale", slug: "armovani-metallospiralyu-ua", parent: "rukava-z-polihlorvinilu" },
  { id: "armovani-pvh-stallyu-ua", name: "Armuotos PVC spirale", slug: "armovani-pvh-stallyu-ua", parent: "rukava-z-polihlorvinilu" },
  { id: "rukava-z-poliuretanu", name: "PUR žarnos", slug: "rukava-z-poliuretanu", parent: null },
  { id: "armovani-metallospiralyu", name: "Armuotos metalo spirale", slug: "armovani-metallospiralyu", parent: "rukava-z-poliuretanu" },
  { id: "armovani-pvh-stallyu", name: "Armuotos PVC spirale", slug: "armovani-pvh-stallyu", parent: "rukava-z-poliuretanu" },
  { id: "bez-spirali", name: "Be spiralės (FLAT)", slug: "bez-spirali", parent: "rukava-z-poliuretanu" },
  { id: "silske-gospodarstvo", name: "Žemės ūkis", slug: "silske-gospodarstvo", parent: null },
  { id: "dlya-grnulyatoriv", name: "Granuliatoriams", slug: "dlya-grnulyatoriv", parent: "silske-gospodarstvo" },
  { id: "dlya-transportuvannya-zernovih", name: "Grūdų transportavimui", slug: "dlya-transportuvannya-zernovih", parent: "silske-gospodarstvo" },
  { id: "dlya-pnevmotransportu", name: "Pneumotransportui", slug: "dlya-pnevmotransportu", parent: "silske-gospodarstvo" },
  { id: "dlya-opriskuvachiv-a-himichnih-dobriv", name: "Purkštuvams ir cheminėms trąšoms", slug: "dlya-opriskuvachiv-a-himichnih-dobriv", parent: "silske-gospodarstvo" },
  { id: "dlya-siyalok", name: "Sėjamosioms", slug: "dlya-siyalok", parent: "silske-gospodarstvo" },
  { id: "dlya-vibroprosivnih-mashin", name: "Vibracinėms sijojimo mašinoms", slug: "dlya-vibroprosivnih-mashin", parent: "silske-gospodarstvo" },
  { id: "dlya-zemlesnaryadiv-i-motopomp", name: "Žemsiurbėms ir motopompoms", slug: "dlya-zemlesnaryadiv-i-motopomp", parent: "silske-gospodarstvo" },
  { id: "specztehnika-2", name: "Specialioji technika", slug: "specztehnika-2", parent: null },
  { id: "dlya-asenizaczii", name: "Asenizacijai", slug: "dlya-asenizaczii", parent: "specztehnika-2" },
  { id: "dlya-dorozhnih-vakuumnih-pilotyagiv", name: "Kelių vakuuminiams siurbliams", slug: "dlya-dorozhnih-vakuumnih-pilotyagiv", parent: "specztehnika-2" },
  { id: "dlya-komunalnoi-tehniki", name: "Komunalinei technikai", slug: "dlya-komunalnoi-tehniki", parent: "specztehnika-2" },
  { id: "dlya-motopomp-ua", name: "Motopompoms", slug: "dlya-motopomp-ua", parent: "specztehnika-2" },
  { id: "ventilyacziya", name: "Vėdinimas", slug: "ventilyacziya", parent: null },
  { id: "dlya-visokih-temperatur", name: "Aukštoms temperatūroms", slug: "dlya-visokih-temperatur", parent: "ventilyacziya" },
  { id: "dlya-himichnih-viparyuvan", name: "Cheminiams garavimams", slug: "dlya-himichnih-viparyuvan", parent: "ventilyacziya" },
  { id: "dlya-shaht-iz-zagrozoyu-vibuhu", name: "Sprogioms šachtoms", slug: "dlya-shaht-iz-zagrozoyu-vibuhu", parent: "ventilyacziya" },
  { id: "dlya-nizkih-temperatur", name: "Žemoms temperatūroms", slug: "dlya-nizkih-temperatur", parent: "ventilyacziya" },
  { id: "vihlopni-gazi", name: "Išmetamosios dujos", slug: "vihlopni-gazi", parent: null },
  { id: "dlya-visokih-temperatur-2", name: "Aukštoms temperatūroms", slug: "dlya-visokih-temperatur-2", parent: "vihlopni-gazi" },
  { id: "poleuretan", name: "Poliuretanas (DEPTAK)", slug: "poleuretan", parent: "vihlopni-gazi" },
  { id: "tpr", name: "TPR", slug: "tpr", parent: "vihlopni-gazi" },
];

const byId = new Map(categories.map((c) => [c.id, c]));
export const categoryById = (id: string): Category | undefined => byId.get(id);
export const childrenOf = (parentId: string): Category[] =>
  categories.filter((c) => c.parent === parentId);
export const topCategories = (): Category[] => categories.filter((c) => !c.parent);

// Walk to the top-level ancestor of a category.
export function topAncestor(id: string): Category | undefined {
  let cur = byId.get(id);
  const seen = new Set<string>();
  while (cur && cur.parent && byId.has(cur.parent) && !seen.has(cur.id)) {
    seen.add(cur.id);
    cur = byId.get(cur.parent);
  }
  return cur;
}
