// Server-side product catalog, sourced from data/products.json.
//
// The JSON is generated by scripts/scrape-generate.mjs from the original site
// (https://rikomarket.com.ua), translated to Lithuanian. Each product carries a
// primary `category` (top-level material family) plus the full list of category
// memberships in `categories` (material + application areas).
//
// This module reads the filesystem, so it must only be imported from server
// components / server code (never a "use client" file). Client components may
// still `import type { Product }` — types are erased at build time.

import fs from "node:fs";
import path from "node:path";
import { childrenOf, categoryById } from "@/lib/categories";
import { defaultLocale, type Locale } from "@/lib/i18n";

export type DescLine = { text: string; heading: boolean };
export type SpecTable = { headers: string[]; rows: string[][] };

export type Product = {
  slug: string;
  name: string;
  category: string; // primary (top-level) category id — see lib/categories.ts
  categories: string[]; // every category id this product belongs to
  subcategory: string; // material sub-category name, if any
  industries: string[];
  color: string; // visual swatch hint: navy | red | silver
  featured: boolean;
  image: string; // path under /public, e.g. /products/orig/clin-vt.jpg
  shortNote: string;
  description: string; // full prose, lines joined with "\n"
  descLines: DescLine[]; // structured prose (heading vs body lines)
  // Technical specifications (any may be empty)
  dn: string;
  temp: string;
  pressure: string;
  vacuum: string;
  wallThickness: string;
  bendRadius: string;
  standardLength: string;
  material: string;
  reinforcement: string;
  colorsAvailable: string;
  certifications: string;
  origin: string;
  sizes: string[];
  specTable: SpecTable | null; // original dimensions table, if present
};

// One file per locale; data/products.ru.json is generated from the Lithuanian
// catalogue by scripts/translate-ru.mjs and keeps the same slugs and shape.
const DATA_PATH: Record<Locale, string> = {
  lt: path.join(process.cwd(), "data", "products.json"),
  ru: path.join(process.cwd(), "data", "products.ru.json"),
};

const cache: Partial<Record<Locale, Product[]>> = {};

export function getAllProducts(locale: Locale = defaultLocale): Product[] {
  const hit = cache[locale];
  if (hit) return hit;
  const list = JSON.parse(fs.readFileSync(DATA_PATH[locale], "utf8")) as Product[];
  cache[locale] = list;
  return list;
}

export function getProductBySlug(slug: string, locale: Locale = defaultLocale): Product | undefined {
  return getAllProducts(locale).find((p) => p.slug === slug);
}

// All category ids in the subtree rooted at `categoryId` (inclusive).
function subtreeIds(categoryId: string): Set<string> {
  const ids = new Set<string>([categoryId]);
  const walk = (id: string) => {
    for (const child of childrenOf(id)) {
      if (!ids.has(child.id)) {
        ids.add(child.id);
        walk(child.id);
      }
    }
  };
  walk(categoryId);
  return ids;
}

// Products belonging to a category or any of its descendants.
export function getProductsByCategory(
  categoryId: string,
  locale: Locale = defaultLocale,
): Product[] {
  const ids = subtreeIds(categoryId);
  return getAllProducts(locale).filter(
    (p) => p.category === categoryId || p.categories.some((c) => ids.has(c)),
  );
}

// Every ancestor of a category (inclusive), walking up `parent` links.
function withAncestors(id: string): string[] {
  const out: string[] = [];
  let cur = categoryById(id);
  const seen = new Set<string>();
  while (cur && !seen.has(cur.id)) {
    seen.add(cur.id);
    out.push(cur.id);
    cur = cur.parent ? categoryById(cur.parent) : undefined;
  }
  return out;
}

// Count of products per category. A category's count includes every product
// anywhere in its subtree (counts roll up to ancestors, deduped per product).
export function countByCategory(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const p of getAllProducts()) {
    const effective = new Set<string>();
    for (const id of [p.category, ...p.categories]) {
      for (const anc of withAncestors(id)) effective.add(anc);
    }
    for (const id of effective) counts[id] = (counts[id] ?? 0) + 1;
  }
  return counts;
}
