// Build the Russian catalogue: data/products.ru.json (same shape as
// data/products.json, every human-readable string swapped for its Russian
// counterpart) and lib/chem-ru.ts (Russian names for the chemical-resistance
// table). The dictionary is scripts/translations-ru.json — a flat LT → RU map
// produced from the Lithuanian catalogue and the Ukrainian originals.
//
//   node scripts/scrape-generate.mjs   # LT catalogue first
//   node scripts/translate-ru.mjs      # then the RU overlay
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const dict = JSON.parse(fs.readFileSync(path.join(ROOT, "scripts", "translations-ru.json"), "utf8"));
const products = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "products.json"), "utf8"));

const misses = new Map();
const tr = (s) => {
  if (typeof s !== "string" || !s.trim()) return s;
  const hit = dict[s.trim()];
  if (hit === undefined) {
    if (/[A-Za-zĄČĘĖĮŠŲŪŽąčęėįšųūž]/.test(s)) misses.set(s, (misses.get(s) ?? 0) + 1);
    return s;
  }
  return hit;
};

const TEXT_FIELDS = ["name", "subcategory", "shortNote", "dn", "temp", "pressure",
  "wallThickness", "standardLength", "vacuum", "bendRadius", "material",
  "reinforcement", "colorsAvailable", "certifications", "origin"];

const ru = products.map((p) => {
  const out = { ...p };
  for (const f of TEXT_FIELDS) out[f] = tr(p[f]);
  out.descLines = (p.descLines ?? []).map((l) => ({ text: tr(l.text), heading: l.heading }));
  out.description = out.descLines.map((l) => l.text).join("\n");
  out.sizes = (p.sizes ?? []).map(tr);
  out.specTable = p.specTable
    ? { headers: p.specTable.headers.map(tr), rows: p.specTable.rows.map((r) => r.map(tr)) }
    : null;
  return out;
});

fs.writeFileSync(path.join(ROOT, "data", "products.ru.json"), JSON.stringify(ru, null, 2) + "\n");

// Russian labels for the chemical-resistance table (lib/chem-data.ts stays LT).
const chemSrc = fs.readFileSync(path.join(ROOT, "lib", "chem-data.ts"), "utf8");
const names = [...chemSrc.matchAll(/\{"name":"((?:[^"\\]|\\.)*)"/g)].map((m) => JSON.parse(`"${m[1]}"`));
const materials = JSON.parse(
  "[" + chemSrc.match(/export const chemMaterials = \[([\s\S]*?)\] as const;/)[1].replace(/,\s*$/, "") + "]",
);
const nameMap = Object.fromEntries(names.map((n) => [n, tr(n)]));
fs.writeFileSync(
  path.join(ROOT, "lib", "chem-ru.ts"),
  `// Russian labels for the chemical-resistance table — generated by\n` +
  `// scripts/translate-ru.mjs, do not edit by hand.\n\n` +
  `export const chemMaterialsRu: string[] = ${JSON.stringify(materials.map(tr), null, 2)};\n\n` +
  `export const chemNameRu: Record<string, string> = ${JSON.stringify(nameMap, null, 2)};\n`,
);

const missArr = [...misses.entries()].sort((a, b) => b[1] - a[1]);
console.log(`products.ru.json: ${ru.length} products`);
console.log(`chem-ru.ts: ${materials.length} materials, ${names.length} substances`);
console.log(`untranslated strings: ${missArr.length}`);
for (const [s, n] of missArr.slice(0, 25)) console.log(`  (${n}) ${s.slice(0, 90)}`);
